model: "GarNet"
labels: &labels [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
                 "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w",
                 "x", "y", "z", "'"]
residual_dense: &dr false
num_sub_blocks: &rep 4

optimization:
    warmup_epochs: 1
    min_lr: 1e-5
    params:
        num_epochs: 100
        lr: 1e-3
        weight_decay: 1e-5
        larc: false
        larc_eta: 1e-3
        luc: false
        luc_eta: 1e-3
        betas: [0.95, 0.98]

AudioToTextDataLayer:
    train:
        sample_rate: &sr 16000
        trim_silence: &ts true
        normalize_transcripts: &nt true
        shuffle: true
        max_duration: 16.7
        drop_last: false
        labels: *labels

    eval:
        sample_rate: *sr
        trim_silence: *ts
        normalize_transcripts: *nt
        shuffle: false
        max_duration: null
        drop_last: false
        labels: *labels

AudioPreprocessing:
    sample_rate: *sr
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: &feat_in 64
    feat_type: "logfbank"
    dither: 0.00001
    pad_to: 16
    stft_conv: true

SpectrogramAugmentation:
    rect_masks: 2
    rect_time: 120
    rect_freq: 50

JasperEncoder:
    activation: "relu"
    conv_mask: true
    load: false
    freeze: false
    feat_in: *feat_in

    # quartz 15x5
    jasper:
        - filters: 256
          repeat: 1
          kernel: [11]
          stride: [2]
          dilation: [1]
          dropout: 0.2
          residual: false

        - filters: 256
          repeat: *rep
          kernel: [11]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 256
          repeat: *rep
          kernel: [11]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 384
          repeat: *rep
          kernel: [13]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 384
          repeat: *rep
          kernel: [13]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 512
          repeat: *rep
          kernel: [17]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 512
          repeat: *rep
          kernel: [17]
          stride: [1]
          dilation: [1]
          dropout: 0.2
          residual: true
          residual_dense: *dr

        - filters: 640
          repeat: *rep
          kernel: [21]
          stride: [1]
          dilation: [1]
          dropout: 0.3
          residual: true
          residual_dense: *dr

        - filters: 640
          repeat: *rep
          kernel: [21]
          stride: [1]
          dilation: [1]
          dropout: 0.3
          residual: true
          residual_dense: *dr

        - filters: 768
          repeat: *rep
          kernel: [25]
          stride: [1]
          dilation: [1]
          dropout: 0.3
          residual: true
          residual_dense: *dr

        - filters: 768
          repeat: *rep
          kernel: [25]
          stride: [1]
          dilation: [1]
          dropout: 0.3
          residual: true
          residual_dense: *dr

        - filters: 896
          repeat: 1
          kernel: [29]
          stride: [1]
          dilation: [2]
          dropout: 0.4
          residual: false

        - filters: 1024
          repeat: 1
          kernel: [1]
          stride: [1]
          dilation: [1]
          dropout: 0.4
          residual: false
